"""Add price to events

Revision ID: 484373918f0e
Revises: 0001_initial
"""
from alembic import op
import sqlalchemy as sa


revision = '484373918f0e'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('price', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'price')
    # ### end Alembic commands ###

